apiVersion: apps/v1
kind: Deployment
metadata:
  name: education-platform
  namespace: education-platform
  labels:
    app: education-platform
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: education-platform
  template:
    metadata:
      labels:
        app: education-platform
        tier: web
    spec:
      containers:
        - name: education-platform
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            # - name: DATABASE_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: education-platform-secrets
            #       key: DATABASE_URL
            # - name: REDIS_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: education-platform-secrets
            #       key: REDIS_URL
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "512Mi"
      restartPolicy: Always
