apiVersion: apps/v1
kind: Deployment
metadata:
  name: education-platform-green
  namespace: education-platform
  labels:
    app: education-platform
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: education-platform
      version: green
  template:
    metadata:
      labels:
        app: education-platform
        version: green
    spec:
      containers:
        - name: education-platform
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
