name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: |-
            .next/cache
          key: next-${{ runner.os }}-${{ hashFiles('package-lock.json', 'next.config.mjs') }}
          restore-keys: |
            next-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint -- --max-warnings=0

      - name: Unit tests
        run: npm run test -- --ci --coverage --passWithNoTests

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: '1'
        run: npm run build
